### ISSUE TITLE
not updating any notes 

### ISSUE THREAD

**Issue by anneliese-mm** [jzohrab/anki-backlog#1]
hi! not working in Version ⁨2.1.65 (aa9a734f)⁩
Python 3.9.15 Qt 6.5.0 PyQt 6.5.0

using tools "Backlog due cards" gives "No notes updated" even when there are notes due 
![Pasted Graphic 1](https://github.com/jzohrab/anki-backlog/assets/75629510/c338532b-b4db-4f20-9182-0a1082732057)

**Comment by jzohrab** [comment]
Hello @anneliese-mm and thanks for the issue!  Did you configure the add on to handle this deck?  Please copy and paste your config here so I can check it out.  Cheers! Jz

**Comment by anneliese-mm** [comment]
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
    Platform: macOS-13.5-x86_64-i386-64bit
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2023-08-27 20:38:33
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Backlog Management ['1480367353', 2022-06-05T18:07, 'None', '']
    Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T11:06, 'None', '']
    Customize Keyboard Shortcuts ['24411424', 2022-09-14T05:12, 'None', '']
    Edit Field During Review Cloze ['385888438', 2023-07-31T09:21, '6.15', mod]
    Image Occlusion Enhanced ['1374772155', 2022-04-09T03:15, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1374772155 1480367353 24411424 385888438 594329229
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by anneliese-mm** [comment]
{
    "decks": [
        {
            "deck": "deck_1_name_as_used_in_browser_search",
            "release-by": "oldest",
            "release-size": 10
        },
        {
            "deck": "deck_2",
            "release-by": "newest",
            "release-size": 20
        }
    ]
}

**Comment by jzohrab** [comment]
Right, you need to configure the add in. That config was the sample. Give that a shot. :-)

**Comment by jzohrab** [comment]
Hi @anneliese-mm , see the config docs at https://github.com/jzohrab/anki-backlog/blob/main/config.md.  If that's not clear enough, let me know.

**Comment by anneliese-mm** [comment]
hi! got there config right but now it displays this error 
<img width="267" alt="image" src="https://github.com/jzohrab/anki-backlog/assets/75629510/a648d5d0-e17d-43d7-a088-100bbb1faaa6">

**Comment by anneliese-mm** [comment]
I think it worked,  but im worried this error means something will be messed up in my cards?

**Comment by jzohrab** [comment]
I don't believe your cards will be messed up. That error is the database guarding itself.  The add in only uses a built in anki api, it doesn't touch the database itself directly.

**Comment by jzohrab** [comment]
Closing, assuming everything is fine! :-)
